apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-storage
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-config
      containers:
        - name: storage-container
          image: amanecopse/p-ser-storage
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/share"
              name: app-config