apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-ns
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./namespace.yaml
  - ./volume.yaml
commonLabels:
  app: p-ser-storage
configMapGenerator:
  - name: app-config
    files:
      - config/application.yaml