apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  labels:
    name: storage-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "storage"
  #  추후에 nfs로 변경할 것
  hostPath:
    path: /run/desktop/mnt/host/c/workspace/p-ser-storage/k8s/config/storage
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  selector:
    matchLabels:
      name: storage-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "storage"